
//socket event names

const CONNECT = 'connect';//MUST BE LOWER CASE!!!!!! 'connect' eventName is a native event... can't customize it
const UPDATE_CHESS_STORE = 'UPDATE_CHESS_STORE';//WHY CANT I FRIGGIN DO EXPORT!!>!>?!?!?!?!?  :LDSFJ:SLDFJ:LDSJF:LSKJ
//IS IT BECAUSE SERVER IS USING THIS?!?!?!?!?!?!?  THIS IS SO FUCKING ANNOYING
const UPDATE_PIECES = 'UPDATE_PIECES';
const UPDATE_TURN = 'UPDATE_TURN';
const NEW_PLAYER = 'NEW_PLAYER';
const UPDATE_PLAYERS_STORE = 'UPDATE_PLAYERS_STORE';
// const SEND_SOCKETID = 'SEND_SOCKETID'; //no need for this



// action creator constants

const CHANGE_CH_STATE='CHANGE_CH_STATE';
const CHANGE_CH_TURN='CHANGE_CH_TURN';
const CHANGE_CH_STATE_EVERYTHING='CHANGE_CH_STATE_EVERYTHING';
const CHANGE_PLAYERS_STATE='CHANGE_PLAYERS_STATE';
const SET_CURR_ID='SET_CURR_ID';


module.exports = {
  CONNECT,
  UPDATE_CHESS_STORE,
  UPDATE_PIECES,
  UPDATE_TURN,
  CHANGE_CH_STATE,
  CHANGE_CH_TURN,
  CHANGE_CH_STATE_EVERYTHING,
  NEW_PLAYER,
  CHANGE_PLAYERS_STATE,
  UPDATE_PLAYERS_STORE,
  SET_CURR_ID,
};
